---
# Tasks for the quantum controller node

- name: Install packages for quantum
  yum: name={{ item }} state=installed
  with_items:
   - openstack-quantum
   - openstack-quantum-openvswitch


- name: Enable ipv4 forwarding in the host
  sysctl: name=net.ipv4.ip_forward value=1 reload=yes

- name: Setup DB for quantum
  shell: /usr/bin/quantum-server-setup -q {{ quantum_db_pass }} -r " " -u quantum --plugin openvswitch -y
         creates=/var/lib/mysql/ovs_quantum

- name: Give right to quantum user.
  mysql_user: name=quantum password={{ quantum_db_pass }} priv=*.*:ALL host='localhost' state=present

- name: Give right to quantum user.
  mysql_user: name=quantum password={{ quantum_db_pass }} priv=*.*:ALL host='%' state=present

- name: Copy the quantum.conf  configuration files 
  template: src=quantum.conf.j2 dest=/etc/quantum/quantum.conf
  notify:  restart quantum
  tags: test

- name: Copy the quantum dhcp agent configuration files 
  template: src=dhcp_agent.ini.j2 dest=/etc/quantum/dhcp_agent.ini
  notify:  restart quantum

- name: Copy the quantum metadata agent configuration file
  template: src=metadata_agent.ini.j2 dest=/etc/quantum/metadata_agent.ini
  notify: restart quantum

- name: Copy the quantum ovs agent configuration files 
  template: src=ovs_quantum_plugin.ini.j2 dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini

- name: copy configuration file for nova
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf
  notify: restart nova

- name: Ensure quantum-ovs-cleanup runs at boot
  service: name=quantum-ovs-cleanup enabled=yes

- name: Start the quantum services
  service: name={{ item }} state=started enabled=yes
  with_items:
   - quantum-server
   - quantum-dhcp-agent
   - quantum-openvswitch-agent
   - quantum-metadata-agent

