---
# Tasks for the openstack compute nodes

- name: Install the required virtualization packages
  yum: name={{ item }} state=installed
  with_items:
   - http://ceph.com/packages/qemu-kvm/centos/x86_64/qemu-img-0.12.1.2-2.355.el6.2.cuttlefish.x86_64.rpm 
   - qemu-img
   - http://ceph.com/packages/qemu-kvm/centos/x86_64/qemu-kvm-0.12.1.2-2.355.el6.2.cuttlefish.x86_64.rpm
   - http://ceph.com/packages/qemu-kvm/centos/x86_64/qemu-kvm-tools-0.12.1.2-2.355.el6.2.cuttlefish.x86_64.rpm
   - libvirt
   - libvirt-client
   - libvirt-python
   - libguestfs-tools
   - bridge-utils

- name: Make sure yum doe not remove our virt packages with yum upgrade
  lineinfile: dest=/etc/yum.conf regexp='' insertafter=EOF line='exclude= qemu*'

- name: Configure qemu.conf in libvirt
  copy: src=qemu.conf.j2 dest=/etc/libvirt/qemu.conf
  notify: restart libvirtd

- name: service libvirt start
  service: name=libvirtd state=started enabled=yes

- name: create link for the qemu
  file: src=/usr/libexec/qemu-kvm dest=/usr/bin/qemu-system-x86_64 state=link

#Create bridge interface.
- name: Setup networking (interfaces)
  copy: owner=root group=root mode=644 src=ifcfg-br100 dest=/etc/sysconfig/network-scripts/ifcfg-br100

- name: Add the bridge to eth0
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0 regexp='' insertafter=EOF line='BRIDGE=br100'

- name: Install packages for openstack
  yum: name={{ item }} state=installed
  with_items:
   - openstack-nova-compute
   - openstack-nova-network
   - openstack-nova-api

- name: Copy over ceph.conf
  copy: src=ceph.conf dest=/etc/ceph/ceph.conf mode=755

- name: Copy keyfile for cinder for Ceph to be used in compute nodes.
  copy: src=client.volumes.key dest=/root/client.volumes.key mode=0600 

- name: Copy oneLine script to make UUID to box so we can run it manually.
  copy: src=onelinethis.sh dest=/root/onelinethis.sh mode=0700 

- name: Copy the nova configuration files
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf
  notify:  restart nova compute

- name: Give permissions to lock folder
  file: path=/var/lock state=directory owner=root group=root mode=0777

- name: Copy the modified file for key injection bug
  copy: src=guestfs.py dest=/usr/lib/python2.6/site-packages/nova/virt/disk/vfs/
