---
# Creates tenant user and role

- hosts: openstack_controller
  tasks:
   - name: Create Tenant
     keystone_user: token={{ keystone_admin_token }} tenant={{ tenant_name }} tenant_description="New Tenant"
     register: tenant

   - name: Create the user for tenant
     keystone_user: token={{ keystone_admin_token }}  user={{ tenant_username }} tenant={{ tenant_name }} 
                                  password={{ tenant_password }}
  
   - name: Assign role to the created user     
     keystone_user: token={{ keystone_admin_token }} role=admin user={{ tenant_username }} tenant={{ tenant_name }}
   
